### ISSUE TITLE
gf for Config seems incorrect

### ISSUE THREAD

**Issue by FatBoyXPC** [noahfrederick/vim-laravel#10]
I was trying `gf` with `config('services.stripe.secret')` and it seemed to want to open up `config/services/stripe/secret.php` instead of `config/services/stripe.php`.

Edit: I also get the same behavior with `config('app.name')`. This certainly seems like a bug?

![2019-02-23_00 47 50_fatboyxpc](https://user-images.githubusercontent.com/744962/53282394-e8676d80-3704-11e9-9b1a-b21b8ef6774e.gif)

**Comment by noahfrederick** [comment]
Thanks for the report. Yep, definitely unintended. I'll get around to fixing it. Patch welcome in the meantime.

**Comment by FatBoyXPC** [comment]
Thank you so much! Works brilliantly!
