### ISSUE TITLE
No matching autocommands

### ISSUE THREAD

**Issue by FatBoyXPC** [noahfrederick/vim-laravel#13]
I just updated to get the latest fix for `gf` and I get this error message every time I open a new file:

```
"app/Providers/AppServiceProvider.php" 34L, 708C
No matching autocommands
Press ENTER or type command to continue
```

The filename is the file that I open. If it's already open in a buffer this doesn't happen. It doesn't matter if I use fzf.vim or `gf` to open the file. If I comment out `Plug 'noahfrederick/vim-laravel'` I don't get this error anymore.

**Comment by noahfrederick** [comment]
Whoops. Pushed a bad change. Reverted in c31c9b9eed2a89293d8725851a27e61a15369b2c.

**Comment by FatBoyXPC** [comment]
SO FAST!
