### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by tomspeak** [noahfrederick/vim-laravel#14]
Hi,

I have added 

```
Plug 'noahfrederick/vim-composer'
Plug 'noahfrederick/vim-laravel'
```

and ran

`:so %`
`:PlugInstall`

But when I run a new instance of `nvim`, and try `:Artisan`, or `:Eview`, etc, none of the commands exist.

Where have I gone wrong?

Cheers

**Comment by noahfrederick** [comment]
Does the current buffer's file belong to a Laravel project? Those commands are only available in such buffers. Additionally `:Eview` and family require [Projectionist](https://github.com/tpope/vim-projectionist).

**Comment by tomspeak** [comment]
Yeah, a Laravel project ran from ‘laravel new blog’. 

Unfortunately none of the commands appear as potential options, so there are no errors, they simply don’t load. 

Would you mind sharing your Laravel projectionist config?

Is there anything else I need to do to make sure it knows it’s a Laravel project?

Cheers

**Comment by noahfrederick** [comment]
Thanks for the additional info.

> Yeah, a Laravel project ran from ‘laravel new blog’.

Okay, that should be fine, but please confirm you are *editing* a file from the project, e.g., `:e config/app.php`. Note the plug-in doesn't care about your current working directory, just the current buffer.

And please let me know what OS this is. I haven't verified anything works on Windows at all.

> Would you mind sharing your Laravel projectionist config?

Well, the plug-in itself contains the Projectionist config. And Projectionist shouldn't be needed for the plug-in to initialize/detect a project anyway.

> Is there anything else I need to do to make sure it knows it’s a Laravel project?

We detect a Laravel project by looking for (a) `bootstrap/app.php` and (b) `artisan` as parents/siblings of the current buffer's file. Should be good as long as those files are present in the project.

You can see whether the project has been detected or not by checking `b:laravel_root`:

```vim
:echo exists('b:laravel_root')
```

**Comment by tomspeak** [comment]
How odd.

I have triple checked I have the plugins installed and up to date.

I have created another new laravel project via `Laravel Installer 2.0.1`

I then run `:e config/app.php` — none of the commands work.

```
:echo exists('b:laravel_root')``` returns `0`.


System stats:

```
Mac OSX (Latest)
NVIM v0.3.4
```

I tried vim instead of neovim on an off chance that broke it, but still, none of the commands are available.

Any ideas? Any more information you need?

**Comment by noahfrederick** [comment]
Strange. Let's make sure it's getting loaded at all. Could you tell me what this gives you?

```vim
:echo exists('g:loaded_laravel')
```

**Comment by tomspeak** [comment]
That returns `1`.

**Comment by tomspeak** [comment]
That returns `1`.

**Comment by noahfrederick** [comment]
> That returns `1`.

Okay, so presumably the plug-in is installed correctly.

If you're comfortable with Vim Script, see [this function](https://github.com/noahfrederick/vim-laravel/blob/c31c9b9eed2a89293d8725851a27e61a15369b2c/plugin/laravel.vim#L34-L54). Add some debugging statements (e.g., `:echomsg fn | echomsg bootstrap | echomsg artisan`) to see which condition isn't being satisfied. If not, I'll create a branch for you later with some modifications, and you can install that.

**Comment by tomspeak** [comment]
Sorry for the late reply, I've never written VimL  -- does this help at all?

```
function! s:laravel_detect(...) abort
  echo "Checking"
  if exists('b:laravel_root')
    return 1
  endif

  echo "Passed laravel root"

  let fn = fnamemodify(a:0 ? a:1 : expand('%'), ':p')

  echo "Fn is: " . fn

  if !isdirectory(fn)
    let fn = fnamemodify(fn, ':h')
  endif

  let bootstrap = findfile('bootstrap/app.php', escape(fn, ', ') . ';')
  echom "Bootstrap is: " . bootstrap
  let artisan = findfile('artisan', escape(fn, ', ') . ';')
  echom "Artisan is: " . artisan

  if !empty(bootstrap) && !empty(artisan)
    echom "We think bootstrap and artisan IS NOT empty"
    let b:laravel_root = fnamemodify(artisan, ':p:h')
    return 1
  endif

  echom "We think bootstrap and artisan IS empty"
endfunction
```

Initial load:

`We think bootstrap and artisan IS empty`


Ctrl + P:

```
Checking            
                                                                                                                                                                                                
Passed laravel root       
                                                                                                                                                                                          
Fn is: term://.//22477:( /bin/zsh '/var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvimWjMQlj/2' )|'fzf' --color=bg+:#EEEEEE,bg:#FFFFFF,border:#FFFFFF,spinner:#767676,hl:#A8A8A8,fg:#262626,header:#A8A8A8,info:#7
67676,pointer:#767676,marker:#767676,fg+:#262626,prompt:#767676,hl+:#767676 '-m' '--prompt' '~/S/referrals/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvimWjMQlj
/1;#FZF         
                                                                                                                                                                                                    
Bootstrap is: term://.//22477:( /bin/zsh '/var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvimWjMQlj/2' )|'fzf' --color=bg+:#EEEEEE,bg:#FFFFFF,border:#FFFFFF,spinner:#767676,hl:#A8A8A8,fg:#262626,header:#A8A8A8,
info:#767676,pointer:#767676,marker:#767676,fg+:#262626,prompt:#767676,hl+:#767676 '-m' '--prompt' '~/S/referrals/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvi
mWjMQlj/bootstrap/app.php         
                                                                                                                                                                                  
Artisan is: term://.//22477:( /bin/zsh '/var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvimWjMQlj/2' )|'fzf' --color=bg+:#EEEEEE,bg:#FFFFFF,border:#FFFFFF,spinner:#767676,hl:#A8A8A8,fg:#262626,header:#A8A8A8,in
fo:#767676,pointer:#767676,marker:#767676,fg+:#262626,prompt:#767676,hl+:#767676 '-m' '--prompt' '~/S/referrals/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/tf/khl5jhrs3k3djnnvjd8jlqpw0000gn/T/nvimW
jMQlj/artisan                                                  
                                                                                                                                                     
We think bootstrap and artisan IS NOT empty    
                                                                                                                                                                    
Checking 
```

Does this give you any insight? Please let me know if there's any more information I can give.

**Comment by noahfrederick** [comment]
Yes, very helpful, although I am missing specific steps to reproduce that. It looks like you are using FZF, and this is introducing another issue.

Please amend function to this:

```vim
function! s:laravel_detect(...) abort
  echomsg "Detect: " . fnamemodify(a:0 ? a:1 : expand('%'), ':p')
  if exists('b:laravel_root')
    echomsg "Root already set: " . b:laravel_root
    return 1
  endif

  let fn = fnamemodify(a:0 ? a:1 : expand('%'), ':p')

  if !isdirectory(fn)
    let fn = fnamemodify(fn, ':h')
  endif

  echomsg "Fn is: " . fn

  let bootstrap = findfile('bootstrap/app.php', escape(fn, ', ') . ';')
  echomsg "Bootstrap is: " . bootstrap
  let artisan = findfile('artisan', escape(fn, ', ') . ';')
  echomsg "Artisan is: " . artisan

  if !empty(bootstrap) && !empty(artisan)
    echomsg "We think bootstrap and artisan IS NOT empty"
    let b:laravel_root = fnamemodify(artisan, ':p:h')
    echomsg "Root set to: " . b:laravel_root
    return 1
  endif

  echomsg "We think bootstrap and artisan IS empty"
endfunction
```

Start a fresh editing session by exiting nvim and starting it again. Then from your project root, do exactly:

1. `:e bootstrap/app.php`
2. `:Artisan list` (does the command work?)
3. Tell me what is printed by `:messages`

Then start a fresh editing session by exiting nvim and starting it again, and edit the same file using FZF as you did above:

1. Choose file using FZF
2. `:Artisan list` (does the command work?)
3. Tell me what is printed by `:messages`

Thanks.

**Comment by noahfrederick** [comment]
Feel free to reopen if you are still experiencing this issue.
