### ISSUE TITLE
Laravel 8 models directory

### ISSUE THREAD

**Issue by adoxography** [noahfrederick/vim-laravel#17]
Hey there, thanks for making this plugin! I've found it really handy while working on Laravel projects in vim.

Having just upgraded to Laravel 8, I've noticed that the automatic editing feature breaks when it comes to making new models. Laravel 8 [automatically places new models in the `app/Models/` directory if it exists](https://laravel.com/docs/8.x/releases), but `vim-laravel` still tries to open the new model from the `app/` directory instead. It looks like opening models from `app/Models/` if possible was built into the plugin originally, but was removed in #2. Reverting this change fixes things for me in Laravel 8, though there should probably be some kind of check for which version of Laravel is being used so that it doesn't break the plugin for Laravel <8.0 users.

I'm happy to get a PR started, but I'm afraid my vimscript knowledge isn't strong enough to get that version check working. Again, thanks for the work you've put into this plugin!

**Comment by noahfrederick** [comment]
Thanks for bringing this to my attention. Please update to the latest version of both vim-laravel and vim-composer. Should be working as expected both on Laravel 8 and older versions.
