### ISSUE TITLE
Add :Elog to access ./storage/logs/laravel.log

### ISSUE THREAD

**Issue by kiryph** [noahfrederick/vim-laravel#23]
I wonder if it is sensible to add `:Elog` to quickly switch to the log file.

**Comment by noahfrederick** [comment]
I've avoided it because (a) the log path is configurable and so it can't be determined without introspection into the app, and (b) log files are not source code files like the rest of the defined projections are, so it doesn't quite fit conceptually. On the other hand, if 99% of the time you're dealing with the default configuration (the `'single'` driver with the default `'path'`), it may be worth just having it.

**Comment by kiryph** [comment]
Thanks for your thoughts. I see your point.

Could you post a snippet for a vimrc how to configure it individually?

**Comment by noahfrederick** [comment]
Here you go:

```vim
autocmd User ProjectionistDetect
      \ if exists('b:laravel_root') |
      \   call projectionist#append(b:laravel_root, { 'storage/logs/*.log': { 'type': 'log' } }) |
      \ endif
```

**Comment by kiryph** [comment]
Thanks for your snippet. I have added following to my vimrc:
```viml
augroup laravel
    autocmd User ProjectionistDetect
          \ if exists('b:laravel_root') |
          \   call projectionist#append(b:laravel_root, { 'storage/logs/*.log': { 'type': 'log' } }) |
          \   call projectionist#append(b:laravel_root, { 'storage/logs/laravel.log': { 'type': 'log' } }) |
          \ endif
augroup END
```

I have added `storage/logs/laravel.log` as default for `:Elog` as described in https://github.com/tpope/vim-projectionist#navigation-commands (last two sentences):

> ### Navigation commands
> Navigation commands encapsulate editing filenames matching certain patterns. Here are some examples for this very project:
>
>    {
>      "plugin/*.vim": {"type": "plugin"},
>      "autoload/*.vim": {"type": "autoload"},
>      "doc/*.txt": {"type": "doc"},
>      "README.markdown": {"type": "doc"}
>    }
> With these in place, you could use :Eplugin projectionist to edit plugin/projectionist.vim and :Edoc projectionist to edit doc/projectionist.txt. **If no argument is given**, it will edit an alternate file of that type (see below) **or a projection without a glob. So in this example :Edoc would default to editing README.markdown.**

Thanks again.

I close this issue but maybe other find this useful and the snippet could be added to another location. Typical locations could be `doc/laravel.txt`, `README.md` or the wiki of this GitHub repository.

**Comment by noahfrederick** [comment]
Added documentation to the wiki: [Adding Your Own Navigation Commands](https://github.com/noahfrederick/vim-laravel/wiki/Navigation-Commands#adding-your-own).
