### ISSUE TITLE
Question: Do you mind sharing the color scheme used in the logo? Looks cool!

### ISSUE THREAD

**Issue by ghecho** [noahfrederick/vim-laravel#5]
![Logo](https://camo.githubusercontent.com/a9c9b5112da1a4cc158c8aae261d4d6f1d6d64ec/68747470733a2f2f6e6f616866726564657269636b2e636f6d2f70692f76696d2d6c61726176656c2d38383862793134302d3430613430612e706e67)

**Comment by noahfrederick** [comment]
The image doesn't show a real Vim color scheme, but the colors themselves are based on colors found on [the Laravel website](https://laravel.com/). Feel free to comment here if you make one yourself.

**Comment by ghecho** [comment]
Thanks, I'm considering that. If I find some free time in the future, I will.
