### ISSUE TITLE
Fzf.vim integration?

### ISSUE THREAD

**Issue by jesseleite** [noahfrederick/vim-laravel#8]
Curious if you use fzf.vim?  It would be cool to have fzf.vim integration for fuzzy searching available artisan commands.  Upon selection, it would autofill the artisan command in, but leave you to add flags and/or press enter to execute the command.  Thoughts?

**Comment by noahfrederick** [comment]
I do use fzf. What you describe sounds like the sort of thing I'd rather leave as an exercise to the user, though. To facilitate this, you can now get a dict of available Artisan commands and their descriptions by calling `laravel#app().artisan_commands()`:

```
{'app:name': 'Set the application namespace',
 'auth:clear-resets': 'Flush expired password reset tokens',
 'cache:clear': 'Flush the application cache',
 'cache:forget': 'Remove an item from the cache',
 'cache:table': 'Create a migration for the cache database table',
 " ...
 'storage:link': 'Create a symbolic link from "public/storage" to "storage/app/public"',
 'tinker': 'Interact with your application',
 'up': 'Bring the application out of maintenance mode',
 'vendor:publish': 'Publish any publishable assets from vendor packages',
 'view:clear': 'Clear all compiled view files'}
```

It looks like [fzf.vim's `Commands` command](https://github.com/junegunn/fzf.vim/blob/17d24ae31d119f8bdd88a5149a831ca35baf726c/autoload/fzf/vim.vim#L869-L932) can be adapted pretty easily. Let me know what you come up with. I'll add it to the [wiki](https://github.com/noahfrederick/vim-laravel/wiki).

**Comment by jesseleite** [comment]
@noahfrederick I'm pretty new to vimscript, but I'll give this a shot!  Thanks for taking it this far!

**Comment by noahfrederick** [comment]
[This](https://github.com/noahfrederick/dots/commit/69c0d1fd3bf8268d03dd871ecbb7a0ea798723f9) should get you 90% of the way there. It uses the fzf plugin and some custom functions (originally based on *fzf.vim*, but not compatible anymore). You'll just have to remove or change the call to `s:green()` and convert `return s:fzf(...)` to the equivalent `fzf#run()` invocation.

Let me know if you need any further guidance.

![artisan_fzf](https://user-images.githubusercontent.com/151598/36288317-0bfa8e14-1288-11e8-8fcf-619125e9dffa.png)

**Comment by jesseleite** [comment]
Oh wow, lots to learn from thank you!  While I've been using Vim emulators for years and feel comfortable _using_ Vim, Vimscript is pretty new to me.  I've been working my way through [Learn Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com/), but getting hung up on what I'm sure are simple things.

Like right now I keep getting `<SID> not in a script context`.  I assume it's related to `MyFunction()`, `s:my_function()`, `my#function()` naming.  So much to learn!

**Comment by kiryph** [comment]
A vim plugin for fuzzy matching projectionist targets is https://github.com/c-brenn/fuzzy-projectionist.vim
